# Generated by Django 4.1.4 on 2022-12-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("birth_date", models.DateField(max_length=20)),
            ],
            options={
                "unique_together": {("first_name", "last_name")},
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work",
                    models.CharField(
                        choices=[
                            ("guitarist", "guitarist"),
                            ("drummer", "drummer"),
                            ("singer", "singer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to="people.person",
                    ),
                ),
            ],
        ),
    ]
